### ISSUE TITLE
MuJoCo-MBPO-COPlanner: AttributeError: 'ReplayMemory' object has no attribute 'update_decay_weights'

### ISSUE THREAD

**Issue by sunCityDaa** [si0wang/COPlanner#2]
I see [COPlanner/MuJoCo-MBPO-COPlanner/sac/replay_memory.py](https://github.com/si0wang/COPlanner/blob/master/MuJoCo-MBPO-COPlanner/sac/replay_memory.py), it has no attribute 'update_decay_weights'. Can someone explain it to me?

> Traceback (most recent call last):
>   File "COPlanner/MuJoCo-MBPO-COPlanner/main_mbpo.py", line 373, in <module>
>     main()
>   File "COPlanner/MuJoCo-MBPO-COPlanner/main_mbpo.py", line 369, in main
>     train(args, env_sampler, predict_env, agent, env_pool, model_pool, logger)
>   File "COPlanner/MuJoCo-MBPO-COPlanner/main_mbpo.py", line 129, in train
>     env_pool.update_decay_weights(args)
> AttributeError: 'ReplayMemory' object has no attribute 'update_decay_weights'

**Comment by si0wang** [comment]
Sorry about that. This was a bug and I just deleted this line of code. You can now rerun the code.

**Comment by sunCityDaa** [comment]
Thanks for the speedy response! @si0wang

**Comment by sunCityDaa** [comment]
I have another question. I can't see parameter is_pdml in argparse, is it always 0? I run successfully using 0. I just wanted to confirm with you. @si0wang

**Comment by si0wang** [comment]
Hi, I'm sorry for the inconvenience. This code was modified from a previous project of mine, so some of the parameters and such were not thoroughly cleaned up. You can delete this parameter and run it!

**Comment by sunCityDaa** [comment]
Thanks for your reply!
